
services:
  nginx:
    image: nginx:latest
    hostname: nginx_main
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  web_hello:
    image: docker/welcome-to-docker:latest
    hostname: web_hello
    ports:
      - "8081:80"

  web_chats:
    image: gwendallv/python-flask-demo:latest
    hostname: web_chats
    ports:
      - "8082:5000"
